### ISSUE TITLE
可以让GitHub自己续自己吗？

### ISSUE THREAD

**Issue by pipidaxian** [yujianke100/FC-Workflow-Keep-Alive#1]
如题，不太想用腾讯或者阿里的云函数，直接用GitHub或者用自己的VPS定期运行可以吗？

**Comment by yujianke100** [comment]
自然可以，原理本身就是定期enable一下不让他被断。

**Comment by pipidaxian** [comment]
还有一个小白问题麻烦下，就是我的这个函数运行之后，要怎么才能在自己的GitHub各项目中确认续杯成功了？

**Comment by yujianke100** [comment]
> 还有一个小白问题麻烦下，就是我的这个函数运行之后，要怎么才能在自己的GitHub各项目中确认续杯成功了？

要是没成功，在任务中断前github会发邮件提醒的，没收到邮件就行，剩余活动时间应该是没法直接看到的。
